<script type="text/javascript" src="[% interface %]/lib/jquery/plugins/jquery.dataTables.min.js"></script>
<script type="text/javascript">
//<![CDATA[
    var MSG_DT_FIRST = _("Primeiro");
    var MSG_DT_LAST = _("Último");
    var MSG_DT_NEXT = _("Próximo");
    var MSG_DT_PREVIOUS = _("Anterior");
    var MSG_DT_EMPTY_TABLE = _("Nenhum dados disponível na tabela");
    var MSG_DT_INFO = _("Showing _START_ to _END_ of _TOTAL_");
    var MSG_DT_INFO_EMPTY = _("Nenhum registro para exibir");
    var MSG_DT_INFO_FILTERED = _("(filtrado de _MAX_ total entries)");
    var MSG_DT_LENGTH_MENU = _("Show _MENU_ entries");
    var MSG_DT_LOADING_RECORDS = _("Carregando...");
    var MSG_DT_PROCESSING = _("Processando...");
    var MSG_DT_SEARCH = _("Pesquisar:");
    var MSG_DT_ZERO_RECORDS = _("Nenhum registro correspondente encontrado");
    var CONFIG_EXCLUDE_ARTICLES_FROM_SORT = _("a an the");
//]]>
</script>
<script type="text/javascript" src="[% interface %]/[% theme %]/js/datatables.js"></script>