<fieldset>
 <legend>Campos codificados</legend>
 <p>
 <label>Público-alvo</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Qualquer</option>
 <option value="aud:a">juvenil, geral</option>
 <option value="aud:b">pré-primário (0-5)</option>
 <option value="aud:c">primário (5-8)</option>
 <option value="aud:d">crianças (9-14)</option>
 <option value="aud:e">jovem</option>
 <option value="aud:k">adulto, sério</option>
 <option value="aud:m">adulto, Geral</option>
 <option value="aud:u">desconhecido</option>
 </select>
 </p>
 <p>
 <label>Descrição física</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Qualquer</option>
 <option value="Material-type:r">impressão normal</option>
 <option value="Material-type:d">grande impressão</option>
 <option value="Material-type:e">formato jornal</option>
 <option value="Material-type:f">Braille ou Alfabeto Moon</option>
 <option value="Material-type:g">microimpressão</option>
 <option value="Material-type:h">escrito á mão</option>
 <option value="Material-type:i">multimídia</option>
 <option value="Material-type:j">mini-impressão</option>
 <option value="Material-type:s">recursos eletrônicos</option>
 <option value="Material-type:t">microfilme</option>
 <option value="Material-type:z">outra forma de material textual</option>
 </select>
 </p>
 <p>
 <label>Forma literária</label>
 <select name="limit" class="subtype">
 <option value="" selected="selected" >Qualquer</option>
 <option value="Literature-Code:a">ficção</option>
 <option value="Literature-Code:b">drama</option>
 <option value="Literature-Code:c">ensaios</option>
 <option value="Literature-Code:d">humor, sátira</option>
 <option value="Literature-Code:e">cartas</option>
 <option value="Literature-Code:f">histórias curtas</option>
 <option value="Literature-Code:g">poesia</option>
 <option value="Literature-Code:h">discursos, oratória</option>
 <option value="Literature-Code:i">livreto</option>
 <option value="Literature-Code:y">não é texto literário</option>
 <option value="Literature-Code:z">múltiplas/outras formas literárias</option>
 </select>
 </p>
 <p>
 <label>Biografia</label>
 <select name="limit" class="subtype" size="1">
 <option value="">Qualquer</option>
 <option value="Biography-code:y">material não biográfico</option>
 <option value="Biography-code:a">autobiografia</option>
 <option value="Biography-code:b">biografia pessoal</option>
 <option value="Biography-code:c">biografia colectiva</option>
 <option value="Biography-code:d">contêm dados bibliográficos</option>
 </select>
 </p>
 <p>
 <label>Ilustração</label>
 <select name="limit" class="subtype" size="1">
 <option value="">Qualquer</option>
 <option value="Illustration-Code:a">ilustrações</option>
 <option value="Illustration-Code:b">mapas</option>
 <option value="Illustration-Code:c">retratos</option>
 <option value="Illustration-Code:d">gráficos</option>
 <option value="Illustration-Code:e">planos</option>
 <option value="Illustration-Code:f">placas</option>
 <option value="Illustration-Code:g">música</option>
 <option value="Illustration-Code:h">facsimiles</option>
 <option value="Illustration-Code:i">brasão</option>
 <option value="Illustration-Code:j">tabela genealógica</option>
 <option value="Illustration-Code:k">formulários</option>
 <option value="Illustration-Code:l">exemplos</option>
 <option value="Illustration-Code:m">gravações de som</option>
 <option value="Illustration-Code:n">transparências</option>
 <option value="Illustration-Code:o">iluminações</option>
 <option value="Illustration-Code:y">nehuma ilustração</option>
 </select>
 </p>
 <p>
 <label>Conteúdo</label>
 <select name="limit" class="subtype">
 <option value="" >Qualquer</option>
 <option value="ctype:a" >bibliografia</option>
 <option value="ctype:b" >catálogo</option>
 <option value="ctype:c" >índice</option>
 <option value="ctype:d" >resumo</option>
 <option value="ctype:e" >dicionário</option>
 <option value="ctype:f" >enciclopedia</option>
 <option value="ctype:g" >directório</option>
 <option value="ctype:h" >descrição do projeto</option>
 <option value="ctype:i" >estatísticas</option>
 <option value="ctype:j" >livros de texto programados</option>
 <option value="ctype:k" >patente</option>
 <option value="ctype:l" >padrão</option>
 <option value="ctype:m" >dissertação ou tese</option>
 <option value="ctype:n" >leis e legislação</option>
 <option value="ctype:o" >tabela numerica</option>
 <option value="ctype:p" >relatório técnico</option>
 <option value="ctype:q" >folha de exame</option>
 <option value="ctype:r" >revisão bibliográfica/resenhas</option>
 <option value="ctype:s" >tratados</option>
 <option value="ctype:t" >banda desenhada/desenhos animados</option>
 <option value="ctype:v" >dissertação ou tese (revisado)</option>
 <option value="ctype:w" >texto religioso</option>
 <option value="ctype:z" >outro</option>
 </select>
 </p>
 <p>
 <label>Tipos de vídeo</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Video-mt:a">filme</option>
 <option value="Video-mt:b">projeção visual</option>
 <option value="Video-mt:c">gravação em video</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Periódicos</legend><p>
 <p>
 <label>Tipo de periódico</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer tipo</option>
 <option value="Type-Of-Serial:a">Periódico</option>
 <option value="Type-Of-Serial:b">Série monográfica</option>
 <option value="Type-Of-Serial:c">Jornal</option>
 <option value="Type-Of-Serial:e">Atualizando folha-solta</option>
 <option value="Type-Of-Serial:f">Base de dados</option>
 <option value="Type-Of-Serial:g">Atualizando website</option>
 <option value="Type-Of-Serial:z">Outro</option>
 </select>
 </p>
 <p>
 <label>Periodicidade</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Frequency-code:a">Diariamente</option>
 <option value="Frequency-code:b">Bissemanal</option>
 <option value="Frequency-code:c">Semanal</option>
 <option value="Frequency-code:d">Quinzenalmente</option>
 <option value="Frequency-code:e">Quinzenalmente</option>
 <option value="Frequency-code:f">Mensal</option>
 <option value="Frequency-code:g">Bimestralmente</option>
 <option value="Frequency-code:h">Trimestralmente</option>
 <option value="Frequency-code:i">Três vezes ao ano</option>
 <option value="Frequency-code:j">Semestral</option>
 <option value="Frequency-code:k">Anual</option>
 <option value="Frequency-code:l">Bienal</option>
 <option value="Frequency-code:m">Trienal</option>
 <option value="Frequency-code:n">Três vezes por semana</option>
 <option value="Frequency-code:o">Três vezes ao mês</option>
 <option value="Frequency-code:y">Sem periodicidade</option>
 <option value="Frequency-code:u">Desconhecido</option>
 <option value="Frequency-code:z">Outro</option>
 </select>
 </p>
 <p>
 <label>Regularidade</label>
 <select name="limit" class="subtype">
 <option value="">Qualquer periodicidade</option>
 <option value="Regularity-code:a">regular</option>
 <option value="Regularity-code:b">normalização irregular</option>
 <option value="Regularity-code:y">irregular</option>
 <option value="Regularity-code:u">desconhecido</option>
 </select>
 </p>
</fieldset>

<fieldset>
 <legend>Fotografia</legend>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Graphics-type:a">montagem</option>
 <option value="Graphics-type:b">desenho</option>
 <option value="Graphics-type:c">pintura</option>
 <option value="Graphics-type:d">reprodução fotomecânica</option>
 <option value="Graphics-type:e">fotonegativo</option>
 <option value="Graphics-type:f">fotoimpressão</option>
 <option value="Graphics-type:h">imagem</option>
 <option value="Graphics-type:i">imprimir</option>
 <option value="Graphics-type:k">desenho técnico</option>
 <option value="Graphics-type:z">outro tipo de gráfico não projectado</option>
 </select>
 <select name="limit" class="subtype">
 <option value="">Qualquer</option>
 <option value="Graphics-support:a">canvas</option>
 <option value="Graphics-support:b">quadro de bristol</option>
 <option value="Graphics-support:c">cavalete</option>
 <option value="Graphics-support:d">vidro</option>
 <option value="Graphics-support:j">reboco</option>
 <option value="Graphics-support:k">quadro rígido</option>
 <option value="Graphics-support:l">porcelana</option>
 <option value="Graphics-support:m">pedra</option>
 <option value="Graphics-support:n">madeira</option>
 <option value="Graphics-support:v">coleção mista</option>
 <option value="Graphics-support:e">sínteses</option>
 <option value="Graphics-support:f">skin</option>
 <option value="Graphics-support:g">têxtil</option>
 <option value="Graphics-support:h">metal</option>
 <option value="Graphics-support:i">papel</option>
 <option value="Graphics-support:z">outros</option>
 <option value="Graphics-support:u">desconhecido</option>
 </select>
</fieldset>
